allowVolumeExpansion: true 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app: nfs-client-provisioner
    release: nfs-client-provisioner
  name: nfs-client
  selfLink: /apis/storage.k8s.io/v1/storageclasses/nfs-client
parameters:
  archiveOnDelete: "true"
provisioner: nfs
parameters:
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}" # 此处也可以使用 "${.PVC.namespace}/${.PVC.name}" 来使用pvc的名称作为nfs中真实目录名称
  onDelete: delete
