allowVolumeExpansion: true 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    app: nfs-client-provisioner
    release: nfs-client-provisioner
  name: nfs-client
parameters:
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
  archiveOnDelete: "true"
  onDelete: delete
provisioner: nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
