apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.17.1
    volumeMounts: # 将secret挂载到目录
    - name: config  # 和卷名称一致
      mountPath: /secret/config  # 容器中的挂载点目录
  volumes:
  - name: config  # 卷名称
    secret:
      secretName: secret
